package com.example.application.service;

public interface CalculatorService {
    int calculatePossibleCombinations(String input);
    int add(int a, int b);
    int subtract(int a, int b);
    int multiply(int a, int b);
    int divide(int a, int b);
    int modulo(int a, int b);
    int power(int a, int b);
    int factorial(int a);
    int permutation(int n, int r);
    int combination(int n, int r);
    int gcd(int a, int b);
    int lcm(int a, int b);
    int log(int a, int b);
    int sqrt(int a);
    int cbrt(int a);
    int abs(int a);
    int ceil(double a);
    int floor(double a);
    int round(double a);
    int max(int a, int b);
    int min(int a, int b);
    int random(int a, int b);
    int sum(int[] a);
    int mean(int[] a);
    int median(int[] a);
    int mode(int[] a);
    int range(int[] a);
    int variance(int[] a);
    int standardDeviation(int[] a);
    int correlation(int[] a, int[] b);
    int covariance(int[] a, int[] b);
    int leastSquaresRegression(int[] a, int[] b);
    int exponentialRegression(int[] a, int[] b);
    int logarithmicRegression(int[] a, int[] b);
    int powerRegression(int[] a, int[] b);
    int quadraticRegression(int[] a, int[] b);
    int cubicRegression(int[] a, int[] b);
    int polynomialRegression(int[] a, int[] b);
    int linearInterpolation(int[] a, int[] b, int c);
    int quadraticInterpolation(int[] a, int[] b, int c);
    int cubicInterpolation(int[] a, int[] b, int c);
    int polynomialInterpolation(int[] a, int[] b, int c);
    int linearExtrapolation(int[] a, int[] b, int c);
    int quadraticExtrapolation(int[] a, int[] b, int c);
    int cubicExtrapolation(int[] a, int[] b, int c);
    int polynomialExtrapolation(int[] a, int[] b, int c);
    int linearRegression(int[] a, int[] b);
    int interpolation(int[] a, int[] b, int c);
    int extrapolation(int[] a, int[] b, int c);
}
